language: python

python:
  - "3.7"

before_install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

install:
  - python setup.py install

script:
  - pytest --cov-report xml --cov=alfie alfie/tests/ -p no:warnings
  # -p flag is to silence the internal tensorflow warnings
  # --cov-report to xml to interface with codecov
  # --cov says check the coverage of alfie with the tests in the folder: alfie/tests/ 

after_success:
    - codecov

notifications:
  email: false #don't @ me trav