language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python setup.py install
  - pytest -p no:warnings

after_success:
    - codecov

notifications:
  email: false