language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python setup.py install
  - pytest -p no:warnings
  #- pytest --cov-report xml --cov=alfie tests/ -p no:warnings
  # -p to silence the internal tensorflow warnings
  # try using this: https://pypi.org/project/pytest-cov/

after_success:
    - codecov

notifications:
  email: false