language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python setup.py install
  - python alfie/test_kmerseq.py
  - python alfie/test_seqio.py

after_success:
    - codecov

notifications:
  email: false