language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python setup.py install
  - pytest -p no:warnings --cov-report --cov=alfie/tests/
  #silence the internal tensorflow warnings

after_success:
    - codecov

notifications:
  email: false